baseURL = "https://proximab.github.io/"
contentdir = "sites/resume/content"
languageCode = "en-us"
publishDir = "sites/resume/public"
theme = "hugo-devresume-theme"
title = "Resume"
#googleAnalytics = "UA-XXXXXXX-Y"

[params]
author = "Bartek"
description = "Resume/CV Software Developer"

primaryColor = "#cdc9c3" #54B689"
textPrimaryColor = "#555555" #292929"

[params.profile]
avatar = "IMG-2492.jpg"
enable = true
name = "Bartłomiej Smarzeniec"
tagline = "Junior Software Engineer"

[params.contact]
enable = true
location = "Poland/Rzeszów"

[[params.contact.list]]
icon = "fas fa-phone-square"
text = "+48 796 841 979"
url = "tel:#"
[[params.contact.list]]
icon = "fas fa-envelope-square"
text = "bartek.smarzeniec@gmail.com"
url = "mailto:#"
[[params.contact.list]]
icon = "fas fa-globe"
text = "github.com/proximab"
url = "#"

[params.skills]
enable = true

[[params.skills.list]]
title = "Technical"
[[params.skills.list.items]]
details = "proficient at computer networks, has knowledge about building modern high availability systems on cloud and systems that would need to scale-up eventually"
[[params.skills.list.items]]
details = ".Net, Go, Python, TypeScript"
[[params.skills.list.items]]
details = "Docker, K8s, HELM, Kustomize, Istio, Linkerd, Traefik"
[[params.skills.list.items]]
details = "gRPC, webApi, graphQL, rabbitmq, kafka, mqtt"
[[params.skills.list.items]]
details = "ASP.NET, signalR, Hangfire, Buffalo, Gin, sqlx"
[[params.skills.list.items]]
details = "MSSQL, PostgreSQL, Redis, MongoDb"
[[params.skills.list.items]]
details = "familiar with Azure/GCP basics, AKS/GKE"
[[params.skills.list.items]]
details = "clean-code, object-oriented design"
[[params.skills.list.items]]
details = "designing and implementing databases schemes with good practise. Experienced in writing complex sql queries."

[[params.skills.list]]
title = "Professional"
[[params.skills.list.items]]
details = "Effective communication"
[[params.skills.list.items]]
details = "Team player"
[[params.skills.list.items]]
details = "Strong problem solver"
[[params.skills.list.items]]
details = "Good time management"

[params.education]
enable = true

[[params.education.list]]
dates = "2010 - 2011"
degree = "MSc in Computer Science"
university = "University College London"
[[params.education.list]]
dates = "2007 - 2010"
degree = "BSc Maths and Physics"
university = "Imperial College London"

[params.awards]
enable = true

[[params.awards.list]]
body = "Microsoft lorem ipsum"
date = "2019"
name = "Award Lorem Ipsum"
[[params.awards.list]]
body = "Oracle Aenean"
date = "2017"
name = "Award Donec Sodales"

[params.languages]
enable = true

[[params.languages.list]]
level = "Native"
name = "English"
[[params.languages.list]]
level = "Professional"
name = "Spanish"

[params.interests]
enable = true

[[params.interests.list]]
name = "Climbing"
[[params.interests.list]]
name = "Snowboarding"
[[params.interests.list]]
name = "Photography"
[[params.interests.list]]
name = "Travelling"

[params.summary]
enable = true
text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."

[params.experience]
enable = true

[[params.experience.list]]
company = "Google"
dates = "2019 - Present"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
title = "Senior Software Engineer"
[[params.experience.list.items]]
details = "Lorem ipsum dolor sit amet, consectetuer."
[[params.experience.list.items]]
details = "Aenean commodo ligula eget dolor."
[[params.experience.list.items]]
details = "Etiam ultricies nisi vel augue."

[[params.experience.list]]
company = "Apple"
dates = "2016 - 2019"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
title = "Lead Software Developer"
[[params.experience.list.items]]
details = "Lorem ipsum dolor sit amet, consectetuer."
[[params.experience.list.items]]
details = "Aenean commodo ligula eget dolor."

[[params.experience.list]]
company = "Dropbox"
dates = "2014 - 2016"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
title = "Senior Software Developer"

[[params.experience.list]]
company = "Uber"
dates = "2013 - 2014"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."
title = "Senior Developer"

[[params.experience.list]]
company = "Amazon"
dates = "2014 - 2016"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
title = "Backend Developer"

[[params.experience.list]]
company = "Startup"
dates = "2013 - 2014"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."
title = "Frontend Developer"

[params.projects]
enable = true

[[params.projects.list]]
meta = "Open Source"
tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
title = "Project Lorem Ipsum"

[[params.projects.list]]
meta = "Open Source"
tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."
title = "Project Sed Fringilla"

[[params.projects.list]]
meta = "Open Source"
tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."
title = "Project Praesent"

[params.information]
enable = true

[[params.information.list]]
title = "Papers"
[[params.information.list.items]]
details = "2018 · Lorem Ipsum"
[[params.information.list.items]]
details = "2016 · Sed Fringilla"

[[params.information.list]]
details = "Hiking, Sports especially volleyball, Guitar, Photography, Music, Chess, Just Chilling"
title = "Interests"

[params.social]
enable = true

[[params.social.list]]
icon = "fab fa-github-square"
title = "proximab"
url = "//github.com/ProximaB/"
[[params.social.list]]
icon = "fab fa-linkedin"
title = "Bartłomiej Smarzeniec"
url = "//linkedin.com/in/username"
[[params.social.list]]
icon = "fab fa-twitter-square"
title = "@username"
url = "//twitter.com/username"
